- DESCRIPTION
- R/fit_process.R
- R/plot_combined.R
- R/transform.R
If `phi_pillar2_cases_weekend` is not included in ncov, then everything should run effectively the same as before
> Phi pillar2 cases weekend

- DESCRIPTION
- R/pars.R
Implementation of 26 betas, with new one added on 2021-08-15 for summer hols
> add beta 26

- DESCRIPTION
- R/simulate.R
VE vs death was never implemented in simulations, this PR fixes that
> fix VE vs death

- DESCRIPTION
- R/simulate.R
https://github.com/ncov-ic/ncov-outputs/pull/1766
> allow modifying gradual npi

- DESCRIPTION
- R/simulate.R
> Changes to work with dust 0.9.21

- DESCRIPTION
- R/pars.R
This PR adds a 29th beta, as suggested during last UK-RTM catchup. It accompanies Divya's ncov PR open for merging
> add beta29

- DESCRIPTION
- R/combined.R
Just a small fix needed for https://github.com/ncov-ic/ncov-outputs/pull/1817
> do not need to add death incidence anymore

- DESCRIPTION
- R/data.R
Stops fitting to variant data after July (once Delta has replace Alpha everywhere), and fixes a bug re NI pillar 2 cases
> fix NI pillar 2 cases and stop fitting to variant after July

- DESCRIPTION
- R/fit.R
A minor fix following https://github.com/mrc-ide/sircovid/pull/366
Tagging to review and test: 1. @epiyasin 2. @Divyakanapram
@richfitz and @MJomaba just tagged as they reviewed the sircovid PR
> Change initial step to 0 (for initial seeding)

- DESCRIPTION
- R/plot_combined.R
- man/spim_plot_variant.Rd
Adds a `date_max` option to the variant plot
> Variant date max

- DESCRIPTION
- R/simulate.R
- man/spim_simulate_prepare.Rd
Small PR to accompany ncov-outputs PR https://github.com/ncov-ic/ncov-outputs/pull/1898 
Strain seed date in combined$pars is replaced by new seed date for simulated VOC
> replace seed_date in combined object pars

- DESCRIPTION
- R/fit_process.R
Just skips when nothing to do, should work generally.
> Small fix for restarted multistage fits

- DESCRIPTION
- R/mtp.R
- R/simulate_tools.R
Minor tweaks now that the format has changed
> Tweaks for mtps

- DESCRIPTION
- R/plot_fit.R
Fixes the traces plots, which weren't plotting all of the parameters correctly
> Fix traces

- DESCRIPTION
- R/control.R
- tests/testthat/test-control.R
Tiny fix, as discussed in standup. This would not really have affected anything, just a ~1% speed penalty to the run
> Don't rerun deterministic models

- DESCRIPTION
- R/plot_combined.R
This mainly just ports over the changes made by @thomrawson in https://github.com/mrc-ide/spimalot/pull/184 to the data fits plot to other plots (react, serology, etc)
> Add monthly lines to all combined plots

- DESCRIPTION
- R/data.R
Updates to use new positives_pcr/negatives_pcr for Scotland for BB fitting - these are both by report date so we shift them by 2 days
> Use PCR for Scotland pillar 2 positivies/negatives

- DESCRIPTION
- R/data.R
Basic PR to setup fits to REACT by age
> setup REACT by age

- DESCRIPTION
- R/data.R
- R/plot_combined.R
- man/spim_plot_react.Rd
PR to implement fits to REACT by age
> Fit react by age

- DESCRIPTION
- R/data.R
This aggregates the SUS admissions before adm_backfill_date for all_admission, as these show better how well we fit to admissions in aggregate.
> aggregate admissions by age before adm_backfill_date

- DESCRIPTION
- R/data.R
- R/plot_combined.R
- man/spim_data.Rd
Adds an option to trim_pillar2 instead by setting the first date from which we do not fit to pillar 2.
> Trim pillar2 date

- DESCRIPTION
- R/control.R
- R/fit_process.R
Adapts `extract_severity` so that it can work for multiregion fits
> Severity for multiregion

- DESCRIPTION
- R/combined.R
- R/fit_process.R
Super small PR to extract severity by strain
> Severity by strain

- DESCRIPTION
- R/control.R
- man/spim_control.Rd
- tests/testthat/test-control.R
Requires https://github.com/mrc-ide/mcstate/pull/209
> Add support for adaptive control

- DESCRIPTION
- R/fit_process.R
This ensures the priors used in the restart will appear in the restart forest plot
> Fix restart priors

- DESCRIPTION
- R/vaccination.R
- man/spim_vaccination_data.Rd
More flexible vaccine data function, avoids having to update and hardcode every time there's a new dose number
> Adaptable vacc data function

- DESCRIPTION
- R/control.R
- R/fit.R
- R/fit_process.R
- man/spim_control.Rd
- man/spim_fit_process.Rd
Adds more control options: `demography` and `simulate`. These are along the lines of `severity`.
> Add more control

- DESCRIPTION
- R/combined.R
- R/fit_process.R
- R/plot_combined.R
Moves the intrinsic severity calculation to fit_process, also incorporates the changes in https://github.com/mrc-ide/spimalot/pull/244
> Intrinsic severity added to fit process
